/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用,创建一个映射
        let reg = Laya.ClassUtils.regClass;
        // reg(className,classDef)  class名字 和 路径
    }
}
GameConfig.width = 640;
GameConfig.height = 1136;
GameConfig.scaleMode ="fixedwidth";
GameConfig.screenMode = "none";
GameConfig.alignV = "top";
GameConfig.alignH = "left";
GameConfig.startScene = "";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
