/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import Hello from './HelloLayabox'
import ScrollText from './scrollText'
import LoadImg from './loadImg'

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
        reg('./HelloLayabox.js', Hello)
        reg('./scrollText.js', ScrollText)
        reg('./loadImg.js', LoadImg)
    }
}
GameConfig.width = 750;
GameConfig.height = 1334;
GameConfig.scaleMode = "fixedwidth";
GameConfig.screenMode = "none";
GameConfig.alignV = "top";
GameConfig.alignH = "left";
GameConfig.startScene = "";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
